"""📄 .env file configuration reader (optional, requires python-dotenv)."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from scriptman._internal import log

from .base import ConfigReader
from .env import EnvVarReader

if TYPE_CHECKING:
    from pydantic import BaseModel

# ═══════════════════════════════════════════════════════════════════════════════
# OPTIONAL DEPENDENCY
# ═══════════════════════════════════════════════════════════════════════════════

try:
    import dotenv
except ImportError as e:
    raise ImportError(
        "🚫 .env file support requires python-dotenv. Install with:\n"
        "    pip install scriptman[dotenv]\n"
        "    # or\n"
        "    pip install python-dotenv"
    ) from e


class DotEnvReader(ConfigReader):
    """📄 Read configuration from .env files.

    Requires the 'dotenv' extra: pip install scriptman[dotenv]

    This reader:
    1. Loads variables from a .env file
    2. Parses SCRIPTMAN_* variables like EnvVarReader
    3. Does NOT modify os.environ by default (safe for testing)

    Args:
        path: Path to .env file (default: .env in cwd).
        load_into_env: If True, loads into os.environ (default: False).

    Example:
        >>> reader = DotEnvReader(Path(".env"))
        >>> reader = DotEnvReader(Path(".secrets.env"))
    """

    def __init__(
        self,
        path: Path | None = None,
        load_into_env: bool = False,
    ) -> None:
        self._path = path or Path.cwd() / ".env"
        self._load_into_env = load_into_env

    @property
    def name(self) -> str:
        return "dotenv"

    @property
    def file_path(self) -> Path | None:
        return self._path

    def read(self) -> dict[str, Any]:
        """🔍 Read and parse .env file."""
        if not self._path.exists():
            log.debug(f"📄 .env file not found: {self._path}")
            return {}

        try:
            # Load without affecting os.environ
            values = dotenv.dotenv_values(self._path)

            if self._load_into_env:
                dotenv.load_dotenv(self._path)

            # Filter and parse SCRIPTMAN_* variables
            result: dict[str, Any] = {}
            prefix = EnvVarReader.PREFIX

            for key, value in values.items():
                if not key.startswith(prefix) or value is None:
                    continue

                # Convert SCRIPTMAN_LOGGING__LEVEL -> logging.level
                config_key = key[len(prefix) :].lower().replace("__", ".")
                result[config_key] = EnvVarReader._parse_value(value)

            return EnvVarReader._unflatten(result)
        except Exception as e:
            log.exception(f"⚠️ Failed to read {self._path}: {e}")
            return {}

    def write(self, data: dict[str, Any]) -> None:
        """✍️ Write configuration to .env file."""
        try:
            lines: list[str] = [
                "# Scriptman Configuration",
                "# Generated by scriptman",
                "",
            ]

            flat = self._flatten_to_env(data)
            for key, value in flat.items():
                lines.append(f"{key}={value}")

            self._path.parent.mkdir(parents=True, exist_ok=True)
            self._path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            log.debug(f"✍️ Wrote config to {self._path}")
        except Exception as e:
            log.exception(f"⚠️ Failed to write {self._path}: {e}")
            raise

    def supports_write(self) -> bool:
        return True

    def generate_example(self, schema: type[BaseModel]) -> str:
        """📝 Generate example .env configuration."""
        # Reuse EnvVarReader's example generation
        return EnvVarReader().generate_example(schema)

    @staticmethod
    def _flatten_to_env(data: dict[str, Any], prefix: str = "") -> dict[str, str]:
        """🔄 Flatten nested dict to SCRIPTMAN_* env vars."""
        result: dict[str, str] = {}
        base = EnvVarReader.PREFIX

        for key, value in data.items():
            env_key = f"{prefix}__{key.upper()}" if prefix else f"{base}{key.upper()}"

            if isinstance(value, dict):
                result.update(DotEnvReader._flatten_to_env(value, env_key))
            else:
                # Format value for .env
                result[env_key] = EnvVarReader._format_env_value(value)

        return result


def is_dotenv_available() -> bool:
    """🔍 Check if python-dotenv is installed."""
    try:
        import dotenv  # noqa: F401

        return True
    except ImportError:
        return False


__all__ = ["DotEnvReader", "is_dotenv_available"]
